# monitor
source = ~/.config/hypr/config/monitor.conf

# variables
source = ~/.config/hypr/config/variables.conf

# keybinds
source = ~/.config/hypr/config/keybinds.conf

# exec 
source = ~/.config/hypr/config/exec.conf

# windows 
source = ~/.config/hypr/config/windows.conf

# env
source = ~/.config/hypr/config/env.conf


