[manager]
linemode = "size"

[preview]
max_width = 1000
max_height = 1000

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
