exec-once = echo 'Xft.dpi: 120' | xrdb -merge
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = kitty
exec-once = fcitx5 -d --replace
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = nutstore
exec-once = nm-applet --indicator
exec-once = blueman-applet
# exec-once = bash ~/.config/hypr/mako/start.sh
exec-once = bash ~/.config/hypr/waybar/start.sh
exec-once = bash ~/.config/hypr/swaync/start.sh
exec-once = bash ~/.config/hypr/eww/start.sh
exec-once = bash ~/.config/hypr/autostart.sh

exec-once = gsettings set org.gnome.desktop.interface gtk-theme Adwaita
exec-once = gsettings set org.gnome.desktop.interface color-scheme prefer-dark
